from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `menu` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
        ALTER TABLE `permission` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
        ALTER TABLE `role` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
        ALTER TABLE `user` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `menu` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间';
        ALTER TABLE `role` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL;
        ALTER TABLE `user` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL COMMENT '更新时间';
        ALTER TABLE `permission` MODIFY COLUMN `updated_at` DATETIME(6) NOT NULL;"""


MODELS_STATE = (
    "eJztm21vm0gQgP+K5U85qVdhbMC+b26SU3O6JFXi3p3aVGiBxUbhrbA0tSr/984uXvNi7I"
    "OUGOzwhZDZGdh59m1mF//oO56B7fDtFAeWvuj/0fvRd5GD4SZX8qbXR76fyKmAIM1mqijR"
    "0UISIJ2A1ER2iEFk4FAPLJ9YngtSN7JtKvR0ULTceSKKXOtrhFXizTFZ4AAKPn8BseUa+D"
    "sO+b/+o2pa2DYyVbUM+m4mV8nSZ7Irl/zJFOnbNFX37MhxE2V/SRaeu9G2XEKlc+ziABFM"
    "H0+CiFaf1m7tJ/cormmiElcxZWNgE0U2SblbkoHuuZQf1CZkDs7pW34XByNlNB7KozGosJ"
    "psJMoqdi/xPTZkBG5m/RUrRwTFGgxjwu0bDkJapS145wsUFNNLmeQQQsXzCDmwfQy5IIGY"
    "dJyaKDrou2pjd05oBxclaQ+zf6Z35++nd2eg9Rv1xoPOHPfxm3WRGJdRsAlIOjQqQFyrHy"
    "fAgSCUAAhaOwGysixAeCPB8RjMQvzr/vamGGLKJAfyowsOfjYsnbzp2VZIvrQT6x6K1Gta"
    "aScMv9ppeGfX0//yXM//vn3HKHghmQfsKewB74AxnTLNx9TgpwIN6Y9PKDDUrRJP9Hbpbh"
    "c5opOXIBfNGSvqMfVvvYhcYzcqWlyYfO/S4nCNbmE5ooXFRwEMTbUSvozN/1OsawwLWxT7"
    "D5EiDmW4YqTE1TkU0YQg+1thSeH6Da8pwG48NPSHSBpKElxHggEcJ6ZQkuLLL9U+IosqYL"
    "l+u8COQR3uzfGoNWDpTB3jKT/mMzaHG/NlCCu6osG9MtaamQAcTFCVcIjr1xALrReb+meD"
    "wWj4EMmSIsB1KONyYA8RJmVDUcf33MJgdPcskTFqfqqYjBXgPVFksZVThR5gCkJFBYwvoI"
    "RYDt7BOWOZA22sTd/ym0Njl8QBnTNAj3ZzE0KIiWSWxQ6eGbeuvVwPwD3UZ1fXl/ez6fWH"
    "TN+/mM4uaYnIpMuc9EzONdDmIb1/r2bve/Tf3qfbm8v8ENnozT71aZ1QRDzV9Z5UZKQCUy"
    "7luDLNHfnGM5s7a9m25pZlc0QbWhNecXOzyh8uzUwFcjhwrJBuRoXb3eoaucuZR6+sY10B"
    "e+TqRWHGOhP9sHnac3rRS+drKz4wuDR5Bau/msurs94E2GajKB2pxcy8gEF/xMss0XUWtm"
    "mVtQIL1+Iisgi8aL7ImfFsHW6hHpjEq+b0/nx6wXqams+DV3u3DVJuFGweZJ3cvYXgZ/W6"
    "jYQaO+ZLbyQcaRrcpr1pHUZEtVDW6BBmEaZrVoFkzqwDetoJQHnApxL7vZJQ//U1bGNBfR"
    "Ka/lo4zw+Wjj2Q537kQ/h88pMN5FNxej6E34rxawjkt6eBwLNxHc14B885hWbkflRrRkrx"
    "Gc3IzLJJT035GHOjIBPj7u3OwQKu0WVfda43XfbV9ki3Sx1qBgpLBikKEXaO58Sg4QPGAw"
    "/rLts6saC8y7ZOtGG7I5QDxEr1HqEkCU7FI5RUTF9DyF4wJYQ4qKMxP8JzTqEZuR9lG5Dy"
    "q9R0zICnNzXlWazSBXkWd2Z3nhVxjS7Pal1AtjvPoq1WNddK2zT/wZEiieOHSBaHSvzRZ7"
    "8t6YKPwvDJCwo65r5PPhOb5tFKmk6/RR4Lg9ZAxQ6y7CpENwbN45wICANOTWsPTh+QVBr7"
    "G4PmccriSIOrMkT0K09TeQ7UwaDMD4oGu39PNNj6PdY3mGqDKkgTi+aZSpPhCK6Cbramix"
    "7FrsugcGUSNZg+ZaH09NltvpTrpN23rq9mS6b71rXhjZruPLXceWqy+1H6JDWV8P9SVh9P"
    "BQVp/eonhVTxqA=="
)
